/* Converted from Shadowlands by Fluxurion specially to HeronCore  */

-- alliance warboard spell script linking
DELETE FROM `spell_script_names` WHERE `spell_id`=261654;
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (261654, 'spell_warboard_alliance_261654');

-- alliance warboard gameobject template

DELETE FROM `gameobject_template` WHERE `entry`=281339;
INSERT INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `unk1`, `faction`, `flags`, `size`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `Data0`, `Data1`, `Data2`, `Data3`, `Data4`, `Data5`, `Data6`, `Data7`, `Data8`, `Data9`, `Data10`, `Data11`, `Data12`, `Data13`, `Data14`, `Data15`, `Data16`, `Data17`, `Data18`, `Data19`, `Data20`, `Data21`, `Data22`, `Data23`, `Data24`, `Data25`, `Data26`, `Data27`, `Data28`, `Data29`, `Data30`, `Data31`, `Data32`, `unkInt32`, `AIName`, `ScriptName`, `WorldEffectID`, `StateWorldEffectID`, `SpellVisualID`, `SpellStateVisualID`, `SpellStateAnimID`, `SpellStateAnimKitID`, `MaxVisible`, `IgnoreDynLos`, `MinGold`, `MaxGold`, `VerifiedBuild`) VALUES (281339, 22, 10016, 'Hero\'s Call Board', '', '', '', 12, 0, 1, 0, 0, 0, 0, 0, 0, 261654, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 8830, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32535);

-- alliance warboard spawn
SET @OGUID := 5000000; -- horde is 5000100

-- cleaning first: remove all alliance warboard old and new
DELETE FROM gameobject WHERE id IN (281339, 206111);

-- alliance warboard spawn Stormwind dwarven district
DELETE FROM `gameobject` WHERE `guid` = @OGUID;
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `PhaseId`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`) VALUES
(@OGUID, 281339, 0, 1519, 5148, 0, -8823.8505859375, 630.57293701171875, 94.31772613525390625, 3.839725255966186523, 0, 0, -0.93969249725341796, 0.34202045202255249, 120, 255, 0); -- 281339 (Area: 5148 - Difficulty: 0)

-- alliance warboard spawn Stormwind trade district
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `PhaseId`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`) VALUES
(@OGUID+1, 281339, 0, 1519, 5150, 0, -8341.76953125, 641.7569580078125, 95.85759735107421875, 3.78736734390258789, 0, 0, -0.94832324981689453, 0.317305892705917358, 120, 255, 0); -- 281339 (Area: 5150 - Difficulty: 0)


/* ALLIANCE PlayerChoices, not all there is more data to sniff. */

DELETE FROM `playerchoice` WHERE `ChoiceId`=352;
INSERT INTO `playerchoice` (`ChoiceId`, `UiTextureKitId`, `Question`, `HideWarboardHeader`, `VerifiedBuild`) VALUES
(352, 261, 'The King needs you! Please take a flyer.', 0, 32535);

DELETE FROM `playerchoice_response` WHERE `ChoiceId`=352;
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 956, 2, 1851098, 'Duskwood', 'Join the Night Watch', 'Everlasting night falls over Darkshire, with man-eating wolves and wild worgen threatening the people that live there.$b$bThey need help if they are to survive against the threats that lurk in the shadows.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 972, 1, 1851118, 'Nagrand', 'Stop the Murkblood', 'The Kurenai of Telaar have been framed for the destruction of an orcish outpost by the Murkblood tribe!\n\nHelp the Kurenai restore their reputation and find peace in Outland.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 1429, 0, 1851120, 'Broken Shore', 'Fight the Legion', 'The Burning Legion has returned to Azeroth!', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 939, 2, 1851107, 'Stonetalon Mountains', 'Travel to Stardust Spire', 'The Horde has been relentless in their conquest of Ashenvale.\n\nNow is the time for a decisive counterattack against their hold on Stonetalon Mountains.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 957, 2, 1851113, 'Wetlands', 'Help the Survey Team', 'The enemies of Ironforge seek to exploit the destruction of the Stonewrought Dam.$b$bHelp the survey team deployed to the region understand where our weaknesses exist and how we can help our dwarven allies rebuild.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 970, 2, 1851122, 'Zangarmarsh', 'Assist the Expedition', 'The Cenarion Expedition is currently studying the exotic flora and fauna in the marshes of Zangarmarsh.\n\nHelping them with their mission will also help the Alliance gain a better understanding of Outland.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 976, 2, 1851148, 'Borean Tundra', 'Enlist with the Expedition', 'The war against the Scourge has begun!\n\nBecome an enlisted soldier with the Valiance Expedition. Help the Alliance achieve victory on the western shores of Northrend!', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 977, 2, 1851153, 'Howling Fjord', 'Battle the Vrykul', 'The port town of Valgarde is located in the shadows of Utgarde Keep, and is under constant threat from the vrykul that spill forth from its halls.\n\nOur victory against the Scourge begins with defeating the vrykul and controlling the eastern shores of Northrend!', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 961, 2, 1851096, 'The Cape of Stranglethorn', 'Discover Hidden Artifacts', 'The Explorer\'s League is looking for artifacts that may have been unearthed after the Shattering.$b$bHelp them uncover whatever secrets the lands hold.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 960, 2, 1851103, 'The Hinterlands', 'Help the Wildhammer', 'The Wildhammer clan needs our help protecting their homeland against the Horde.$b$bShow them that their kindness is not forgotten by the Alliance.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 989, 2, 1851133, 'The Jade Forest', 'Report to Stormwind Keep', 'A naval battle between the Alliance and Horde have stranded some of our people on an unknown landmass.$b$bBring them back home.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 1014, 2, 1851147, 'Tanaan Jungle', 'Enter the Dark Portal', 'The Iron Horde are invading Azeroth!\n\nWe must stop them to save our world. For Azeroth!', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 978, 2, 1851151, 'Dragonblight', 'Travel to Dragonblight', 'A direct route into Icecrown exists in the Light-forsaken land of Dragonblight.\n\nSlow the Scourge and give our forces time to build an offensive to lay siege to the Wrathgate.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 979, 2, 1851152, 'Grizzly Hills', 'Assist the Military', 'The Horde are sending their forces to pillage our storehouses, raid our encampments, and strip the land of its resources.\n\nFind what we need to break our stalemate with the Horde.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 978, 1, 1851151, 'Dragonblight', 'Travel to Dragonblight', 'A direct route into Icecrown exists in the Light-forsaken land of Dragonblight.\n\nSlow the Scourge and give our forces time to build an offensive to lay siege to the Wrathgate.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 964, 2, 1851093, 'Badlands', 'Gab with Gek', 'The goblins of Fuselight are looking for adventurers to tame the wilderness surrounding their newly built town.$b$bDeal with the threats to Fuselight, and the Alliance\'s relationship with the Steamwheedle Cartel will flourish.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 945, 2, 1851109, 'Tanaris', 'Convince Gadgetzan', 'The Steamwheedle Cartel is one of the most successful goblin cartels, and we need to establish an Alliance presence in their capital city.\n\nPersuade Marin Noggenfogger that Gadgetzan should side with the Alliance.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 990, 2, 1851139, 'Valley of the Four Winds', 'Travel to the Valley', 'The tale of two pandaren and their exploits around Pandaria is echoed by all that have been to the Valley of the Four Winds.\n\nLearn from the Stormstouts what makes Pandaria special.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 945, 1, 1851109, 'Tanaris', 'Convince Gadgetzan', 'The Steamwheedle Cartel is one of the most successful goblin cartels, and we need to establish an Alliance presence in their capital city.\n\nPersuade Marin Noggenfogger that Gadgetzan should side with the Alliance.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 947, 2, 1851114, 'Winterspring', 'Travel to Winterspring', 'The furbolg of Winterspring are growing increasingly hostile and pose a threat to the Alliance and its allies in the area.\n\nDiscover why the Winterfall furbolg have decided to attack the Alliance.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 991, 2, 1851134, 'Krasarang Wilds', 'Travel to Krasarang', 'The pandaren of Krasarang Wilds have been beset by unrelenting rain and a general malaise has fallen over the land.\n\nAssist the denizens of the Wilds, and find out what is afflicting the otherwise jovial pandaren.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 946, 2, 1851101, 'Felwood', 'Help Cleanse Felwood', 'The Burning Legion\'s corruption still taints Felwood, and its effects can be seen everywhere.\n\nStop the demon infestation and aid the Emerald Circle in cleansing the forest.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 971, 2, 1851121, 'Terokkar Forest', 'Assist Allerian Stronghold', 'The forest to the south of Shattrath City is both beautiful and dangerous.\n\nThe people in Allerian Stronghold will need all the help they can get to survive in Terokkar Forest.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 946, 1, 1851101, 'Felwood', 'Help Cleanse Felwood', 'The Burning Legion\'s corruption still taints Felwood, and its effects can be seen everywhere.\n\nStop the demon infestation and aid the Emerald Circle in cleansing the forest.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 965, 2, 1851105, 'Searing Gorge', 'Investigate the Dwarves', 'Ragnaros\' Dark Iron dwarves are organizing, and appear poised to attack Alliance controlled territories!$b$bWork with the Thorium Brotherhood to uncover their motives and end their incursion.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 942, 2, 1851110, 'Thousand Needles', 'Stop the Grimtotem', 'Flooding caused by the Cataclysm has displaced our allies and emboldened the Grimtotem tribe to encroach on our encampments.\n\nStop the Grimtotem and aid our allies in the region.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 948, 2, 1851111, 'Un\'Goro Crater', 'Assist the Expeditions', 'Un\'Goro Crater is a lush tropical environment that has many unique beasts and crystals all throughout its landscape.\n\nThe Marshal Expeditions is looking for help to study the land and gain a better understanding of the crater.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 943, 2, 1851102, 'Feralas', 'Assist Dreamer\'s Rest', 'An insidious sickness falls over the lands of Feralas, all while the Horde and the Grimtotem tauren assail our encampments.\n\nSee what can be done to quell the Grimtotem threat and cure the land.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 968, 2, 1851100, 'Eastern Plaguelands', 'Travel with Fiona', 'A group of adventurers are traveling to Light\'s Hope Chapel to enlist with the Argent Crusade.$b$bThe caravan leader, Fiona, needs help reaching their destination safely.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 966, 2, 1851094, 'Blasted Lands', 'Stop the Horde', 'Our forces at Nethergarde Keep need reinforcements to hold back the Horde.$b$bTurn the tide of battle in favor of the Alliance!', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 964, 1, 1851093, 'Badlands', 'Gab with Gek', 'The goblins of Fuselight are looking for adventurers to tame the wilderness surrounding their newly built town.$b$bDeal with the threats to Fuselight, and the Alliance\'s relationship with the Steamwheedle Cartel will flourish.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 967, 2, 1851095, 'Burning Steppes', 'Speak with Keeshan', 'The Blackrock clan is poised to attack Redridge and other neighboring lands. The aggression of the Blackrock orcs cannot be left unchecked.$b$bWork with Keeshan to stop the Blackrock from advancing across Eastern Kingdoms.\n', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 962, 2, 1851112, 'Western Plaguelands', 'Defeat the Forsaken', 'The Forsaken have launched a counterattack to cut off Alliance forces and claim Andorhal for themselves!$b$bStop the Scourge, defeat the Horde, and reclaim Andorhal for the Alliance!', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 941, 1, 1851097, 'Desolace', 'Lend Aid to Desolace', 'We cannot afford to encounter any surprises as we advance our campaign to secure Desolace.\n\nSee that Desolace is placed under the banner of the Alliance.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 957, 1, 1851113, 'Wetlands', 'Help the Survey Team', 'The enemies of Ironforge seek to exploit the destruction of the Stonewrought Dam.$b$bHelp the survey team deployed to the region understand where our weaknesses exist and how we can help our dwarven allies rebuild.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 940, 1, 1851087, 'Southern Barrens', 'Aid Northwatch Hold', 'The Alliance has encountered heavy Horde resistance in the Southern Barrens.\n\nWe must hold against the Horde if we have any hope of pushing them out of Kalimdor and keeping our supply routes secure.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 941, 2, 1851097, 'Desolace', 'Lend Aid to Desolace', 'We cannot afford to encounter any surprises as we advance our campaign to secure Desolace.\n\nSee that Desolace is placed under the banner of the Alliance.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 969, 1, 1851116, 'Hellfire Peninsula', 'Travel to Outland', 'The Dark Portal has reopened and the Burning Legion is now positioned to attack Azeroth yet again.\n\nStop the demon filth from taking control of the Dark Portal and cutting off supplies to our forces in Hellfire Peninsula.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 940, 2, 1851087, 'Southern Barrens', 'Aid Northwatch Hold', 'The Alliance has encountered heavy Horde resistance in the Southern Barrens.\n\nWe must hold against the Horde if we have any hope of pushing them out of Kalimdor and keeping our supply routes secure.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 970, 1, 1851122, 'Zangarmarsh', 'Assist the Expedition', 'The Cenarion Expedition is currently studying the exotic flora and fauna in the marshes of Zangarmarsh.\n\nHelping them with their mission will also help the Alliance gain a better understanding of Outland.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 976, 1, 1851148, 'Borean Tundra', 'Enlist with the Expedition', 'The war against the Scourge has begun!\n\nBecome an enlisted soldier with the Valiance Expedition. Help the Alliance achieve victory on the western shores of Northrend!', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 977, 1, 1851153, 'Howling Fjord', 'Battle the Vrykul', 'The port town of Valgarde is located in the shadows of Utgarde Keep, and is under constant threat from the vrykul that spill forth from its halls.\n\nOur victory against the Scourge begins with defeating the vrykul and controlling the eastern shores of Northrend!', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 989, 1, 1851133, 'The Jade Forest', 'Report to Stormwind Keep', 'A naval battle between the Alliance and Horde have stranded some of our people on an unknown landmass.$b$bBring them back home.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 969, 2, 1851116, 'Hellfire Peninsula', 'Travel to Outland', 'The Dark Portal has reopened and the Burning Legion is now positioned to attack Azeroth yet again.\n\nStop the demon filth from taking control of the Dark Portal and cutting off supplies to our forces in Hellfire Peninsula.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 1014, 1, 1851147, 'Tanaan Jungle', 'Enter the Dark Portal', 'The Iron Horde are invading Azeroth!\n\nWe must stop them to save our world. For Azeroth!', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 979, 1, 1851152, 'Grizzly Hills', 'Assist the Military', 'The Horde are sending their forces to pillage our storehouses, raid our encampments, and strip the land of its resources.\n\nFind what we need to break our stalemate with the Horde.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 990, 1, 1851139, 'Valley of the Four Winds', 'Travel to the Valley', 'The tale of two pandaren and their exploits around Pandaria is echoed by all that have been to the Valley of the Four Winds.\n\nLearn from the Stormstouts what makes Pandaria special.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 968, 1, 1851100, 'Eastern Plaguelands', 'Travel with Fiona', 'A group of adventurers are traveling to Light\'s Hope Chapel to enlist with the Argent Crusade.$b$bThe caravan leader, Fiona, needs help reaching their destination safely.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 991, 1, 1851134, 'Krasarang Wilds', 'Travel to Krasarang', 'The pandaren of Krasarang Wilds have been beset by unrelenting rain and a general malaise has fallen over the land.\n\nAssist the denizens of the Wilds, and find out what is afflicting the otherwise jovial pandaren.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 948, 1, 1851111, 'Un\'Goro Crater', 'Assist the Expeditions', 'Un\'Goro Crater is a lush tropical environment that has many unique beasts and crystals all throughout its landscape.\n\nThe Marshal Expeditions is looking for help to study the land and gain a better understanding of the crater.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 962, 1, 1851112, 'Western Plaguelands', 'Defeat the Forsaken', 'The Forsaken have launched a counterattack to cut off Alliance forces and claim Andorhal for themselves!$b$bStop the Scourge, defeat the Horde, and reclaim Andorhal for the Alliance!', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 966, 1, 1851094, 'Blasted Lands', 'Stop the Horde', 'Our forces at Nethergarde Keep need reinforcements to hold back the Horde.$b$bTurn the tide of battle in favor of the Alliance!', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 967, 1, 1851095, 'Burning Steppes', 'Speak with Keeshan', 'The Blackrock clan is poised to attack Redridge and other neighboring lands. The aggression of the Blackrock orcs cannot be left unchecked.$b$bWork with Keeshan to stop the Blackrock from advancing across Eastern Kingdoms.\n', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 965, 1, 1851105, 'Searing Gorge', 'Investigate the Dwarves', 'Ragnaros\' Dark Iron dwarves are organizing, and appear poised to attack Alliance controlled territories!$b$bWork with the Thorium Brotherhood to uncover their motives and end their incursion.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 942, 1, 1851110, 'Thousand Needles', 'Stop the Grimtotem', 'Flooding caused by the Cataclysm has displaced our allies and emboldened the Grimtotem tribe to encroach on our encampments.\n\nStop the Grimtotem and aid our allies in the region.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 943, 1, 1851102, 'Feralas', 'Assist Dreamer\'s Rest', 'An insidious sickness falls over the lands of Feralas, all while the Horde and the Grimtotem tauren assail our encampments.\n\nSee what can be done to quell the Grimtotem threat and cure the land.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 971, 1, 1851121, 'Terokkar Forest', 'Assist Allerian Stronghold', 'The forest to the south of Shattrath City is both beautiful and dangerous.\n\nThe people in Allerian Stronghold will need all the help they can get to survive in Terokkar Forest.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 947, 1, 1851114, 'Winterspring', 'Travel to Winterspring', 'The furbolg of Winterspring are growing increasingly hostile and pose a threat to the Alliance and its allies in the area.\n\nDiscover why the Winterfall furbolg have decided to attack the Alliance.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 943, 0, 1851102, 'Feralas', 'Assist Dreamer\'s Rest', 'An insidious sickness falls over the lands of Feralas, all while the Horde and the Grimtotem tauren assail our encampments.\n\nSee what can be done to quell the Grimtotem threat and cure the land.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 958, 0, 1851092, 'Arathi Highlands', 'Support Stromgarde', 'The Horde are advancing on the Highlands after their victory in Hillsbrad.$b$bWe mustn\'t yield! Force them out and halt their advancement across the Eastern Kingdoms.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 958, 1, 1851092, 'Arathi Highlands', 'Support Stromgarde', 'The Horde are advancing on the Highlands after their victory in Hillsbrad.$b$bWe mustn\'t yield! Force them out and halt their advancement across the Eastern Kingdoms.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 963, 0, 1851108, 'Swamp of Sorrows', 'Work with the Baron', 'The trade baron of Bogpaddle needs assistance to make his town a prime destination.$b$bAssist him with whatever tasks he has to secure supplies for the Alliance.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 963, 1, 1851108, 'Swamp of Sorrows', 'Work with the Baron', 'The trade baron of Bogpaddle needs assistance to make his town a prime destination.$b$bAssist him with whatever tasks he has to secure supplies for the Alliance.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 954, 0, 1851085, 'Redridge Mountains', 'Protect Lakeshire', 'The people of Lakeshire are worried that another gnoll attack is about to take place.$b$bPrevent the gnolls from mobilizing and ransacking our city.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 954, 1, 1851085, 'Redridge Mountains', 'Protect Lakeshire', 'The people of Lakeshire are worried that another gnoll attack is about to take place.$b$bPrevent the gnolls from mobilizing and ransacking our city.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 953, 0, 1851081, 'Loch Modan', 'Quell the Trogg Threat', 'The trogg threat to Ironforge has intensified after the destruction of the Stonewrought Dam.$b$bAssist Ironforge\'s defenders with the trogg infestation.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 953, 1, 1851081, 'Loch Modan', 'Quell the Trogg Threat', 'The trogg threat to Ironforge has intensified after the destruction of the Stonewrought Dam.$b$bAssist Ironforge\'s defenders with the trogg infestation.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 960, 0, 1851103, 'The Hinterlands', 'Help the Wildhammer', 'The Wildhammer clan needs our help protecting their homeland against the Horde.$b$bShow them that their kindness is not forgotten by the Alliance.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 960, 1, 1851103, 'The Hinterlands', 'Help the Wildhammer', 'The Wildhammer clan needs our help protecting their homeland against the Horde.$b$bShow them that their kindness is not forgotten by the Alliance.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 956, 0, 1851098, 'Duskwood', 'Join the Night Watch', 'Everlasting night falls over Darkshire, with man-eating wolves and wild worgen threatening the people that live there.$b$bThey need help if they are to survive against the threats that lurk in the shadows.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 956, 1, 1851098, 'Duskwood', 'Join the Night Watch', 'Everlasting night falls over Darkshire, with man-eating wolves and wild worgen threatening the people that live there.$b$bThey need help if they are to survive against the threats that lurk in the shadows.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 961, 0, 1851096, 'The Cape of Stranglethorn', 'Discover Hidden Artifacts', 'The Explorer\'s League is looking for artifacts that may have been unearthed after the Shattering.$b$bHelp them uncover whatever secrets the lands hold.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 957, 0, 1851113, 'Wetlands', 'Help the Survey Team', 'The enemies of Ironforge seek to exploit the destruction of the Stonewrought Dam.$b$bHelp the survey team deployed to the region understand where our weaknesses exist and how we can help our dwarven allies rebuild.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 962, 0, 1851112, 'Western Plaguelands', 'Defeat the Forsaken', 'The Forsaken have launched a counterattack to cut off Alliance forces and claim Andorhal for themselves!$b$bStop the Scourge, defeat the Horde, and reclaim Andorhal for the Alliance!', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 964, 0, 1851093, 'Badlands', 'Gab with Gek', 'The goblins of Fuselight are looking for adventurers to tame the wilderness surrounding their newly built town.$b$bDeal with the threats to Fuselight, and the Alliance\'s relationship with the Steamwheedle Cartel will flourish.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 965, 0, 1851105, 'Searing Gorge', 'Investigate the Dwarves', 'Ragnaros\' Dark Iron dwarves are organizing, and appear poised to attack Alliance controlled territories!$b$bWork with the Thorium Brotherhood to uncover their motives and end their incursion.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 966, 0, 1851094, 'Blasted Lands', 'Stop the Horde', 'Our forces at Nethergarde Keep need reinforcements to hold back the Horde.$b$bTurn the tide of battle in favor of the Alliance!', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 967, 0, 1851095, 'Burning Steppes', 'Speak with Keeshan', 'The Blackrock clan is poised to attack Redridge and other neighboring lands. The aggression of the Blackrock orcs cannot be left unchecked.$b$bWork with Keeshan to stop the Blackrock from advancing across Eastern Kingdoms.\n', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 968, 0, 1851100, 'Eastern Plaguelands', 'Travel with Fiona', 'A group of adventurers are traveling to Light\'s Hope Chapel to enlist with the Argent Crusade.$b$bThe caravan leader, Fiona, needs help reaching their destination safely.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 970, 0, 1851122, 'Zangarmarsh', 'Assist the Expedition', 'The Cenarion Expedition is currently studying the exotic flora and fauna in the marshes of Zangarmarsh.\n\nHelping them with their mission will also help the Alliance gain a better understanding of Outland.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 969, 0, 1851116, 'Hellfire Peninsula', 'Travel to Outland', 'The Dark Portal has reopened and the Burning Legion is now positioned to attack Azeroth yet again.\n\nStop the demon filth from taking control of the Dark Portal and cutting off supplies to our forces in Hellfire Peninsula.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 971, 0, 1851121, 'Terokkar Forest', 'Assist Allerian Stronghold', 'The forest to the south of Shattrath City is both beautiful and dangerous.\n\nThe people in Allerian Stronghold will need all the help they can get to survive in Terokkar Forest.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 972, 0, 1851118, 'Nagrand', 'Stop the Murkblood', 'The Kurenai of Telaar have been framed for the destruction of an orcish outpost by the Murkblood tribe!\n\nHelp the Kurenai restore their reputation and find peace in Outland.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 977, 0, 1851153, 'Howling Fjord', 'Battle the Vrykul', 'The port town of Valgarde is located in the shadows of Utgarde Keep, and is under constant threat from the vrykul that spill forth from its halls.\n\nOur victory against the Scourge begins with defeating the vrykul and controlling the eastern shores of Northrend!', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 972, 2, 1851118, 'Nagrand', 'Stop the Murkblood', 'The Kurenai of Telaar have been framed for the destruction of an orcish outpost by the Murkblood tribe!\n\nHelp the Kurenai restore their reputation and find peace in Outland.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 976, 0, 1851148, 'Borean Tundra', 'Enlist with the Expedition', 'The war against the Scourge has begun!\n\nBecome an enlisted soldier with the Valiance Expedition. Help the Alliance achieve victory on the western shores of Northrend!', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 978, 0, 1851151, 'Dragonblight', 'Travel to Dragonblight', 'A direct route into Icecrown exists in the Light-forsaken land of Dragonblight.\n\nSlow the Scourge and give our forces time to build an offensive to lay siege to the Wrathgate.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 979, 0, 1851152, 'Grizzly Hills', 'Assist the Military', 'The Horde are sending their forces to pillage our storehouses, raid our encampments, and strip the land of its resources.\n\nFind what we need to break our stalemate with the Horde.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 989, 0, 1851133, 'The Jade Forest', 'Report to Stormwind Keep', 'A naval battle between the Alliance and Horde have stranded some of our people on an unknown landmass.$b$bBring them back home.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 990, 0, 1851139, 'Valley of the Four Winds', 'Travel to the Valley', 'The tale of two pandaren and their exploits around Pandaria is echoed by all that have been to the Valley of the Four Winds.\n\nLearn from the Stormstouts what makes Pandaria special.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 991, 0, 1851134, 'Krasarang Wilds', 'Travel to Krasarang', 'The pandaren of Krasarang Wilds have been beset by unrelenting rain and a general malaise has fallen over the land.\n\nAssist the denizens of the Wilds, and find out what is afflicting the otherwise jovial pandaren.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 1014, 0, 1851147, 'Tanaan Jungle', 'Enter the Dark Portal', 'The Iron Horde are invading Azeroth!\n\nWe must stop them to save our world. For Azeroth!', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 1429, 1, 1851120, 'Broken Shore', 'Fight the Legion', 'The Burning Legion has returned to Azeroth!', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 939, 1, 1851107, 'Stonetalon Mountains', 'Travel to Stardust Spire', 'The Horde has been relentless in their conquest of Ashenvale.\n\nNow is the time for a decisive counterattack against their hold on Stonetalon Mountains.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 942, 0, 1851110, 'Thousand Needles', 'Stop the Grimtotem', 'Flooding caused by the Cataclysm has displaced our allies and emboldened the Grimtotem tribe to encroach on our encampments.\n\nStop the Grimtotem and aid our allies in the region.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 949, 2, 1851106, 'Silithus', 'Travel to Silithus', 'The Twilight\'s Hammer and silithid roam the desert of Silithus, terrorizing the Cenarion Circle and adventurers alike.\n\nHelp our allies stop the Twilight\'s Hammer and root out the silithid from their hives.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 944, 2, 1851099, 'Dustwallow Marsh', 'Assist Theramore', 'Theramore is a proud Alliance city in the heart of Horde territory.\n\nThreats from within the city and outside its walls seek to diminish its status on Kalimdor.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 938, 2, 1851070, 'Ashenvale', 'Assist the Sentinels', 'The Horde has sent its forces to Ashenvale, seeking to rout out the night elves that live in the forest.\n\nStop the Horde\'s desecration of the night elf homeland.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 937, 2, 1851074, 'Darkshore', 'Assist the Night Elves', 'The destruction of Auberdine has left the night elves in a vulnerable situation, with many of their own unaccounted for.\n\nLend your support. Help them rebuild.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 947, 0, 1851114, 'Winterspring', 'Travel to Winterspring', 'The furbolg of Winterspring are growing increasingly hostile and pose a threat to the Alliance and its allies in the area.\n\nDiscover why the Winterfall furbolg have decided to attack the Alliance.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 944, 1, 1851099, 'Dustwallow Marsh', 'Assist Theramore', 'Theramore is a proud Alliance city in the heart of Horde territory.\n\nThreats from within the city and outside its walls seek to diminish its status on Kalimdor.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 938, 1, 1851070, 'Ashenvale', 'Assist the Sentinels', 'The Horde has sent its forces to Ashenvale, seeking to rout out the night elves that live in the forest.\n\nStop the Horde\'s desecration of the night elf homeland.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 937, 1, 1851074, 'Darkshore', 'Assist the Night Elves', 'The destruction of Auberdine has left the night elves in a vulnerable situation, with many of their own unaccounted for.\n\nLend your support. Help them rebuild.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 949, 1, 1851106, 'Silithus', 'Travel to Silithus', 'The Twilight\'s Hammer and silithid roam the desert of Silithus, terrorizing the Cenarion Circle and adventurers alike.\n\nHelp our allies stop the Twilight\'s Hammer and root out the silithid from their hives.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 961, 1, 1851096, 'The Cape of Stranglethorn', 'Discover Hidden Artifacts', 'The Explorer\'s League is looking for artifacts that may have been unearthed after the Shattering.$b$bHelp them uncover whatever secrets the lands hold.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 945, 0, 1851109, 'Tanaris', 'Convince Gadgetzan', 'The Steamwheedle Cartel is one of the most successful goblin cartels, and we need to establish an Alliance presence in their capital city.\n\nPersuade Marin Noggenfogger that Gadgetzan should side with the Alliance.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 949, 0, 1851106, 'Silithus', 'Travel to Silithus', 'The Twilight\'s Hammer and silithid roam the desert of Silithus, terrorizing the Cenarion Circle and adventurers alike.\n\nHelp our allies stop the Twilight\'s Hammer and root out the silithid from their hives.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 944, 0, 1851099, 'Dustwallow Marsh', 'Assist Theramore', 'Theramore is a proud Alliance city in the heart of Horde territory.\n\nThreats from within the city and outside its walls seek to diminish its status on Kalimdor.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 938, 0, 1851070, 'Ashenvale', 'Assist the Sentinels', 'The Horde has sent its forces to Ashenvale, seeking to rout out the night elves that live in the forest.\n\nStop the Horde\'s desecration of the night elf homeland.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 937, 0, 1851074, 'Darkshore', 'Assist the Night Elves', 'The destruction of Auberdine has left the night elves in a vulnerable situation, with many of their own unaccounted for.\n\nLend your support. Help them rebuild.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 941, 0, 1851097, 'Desolace', 'Lend Aid to Desolace', 'We cannot afford to encounter any surprises as we advance our campaign to secure Desolace.\n\nSee that Desolace is placed under the banner of the Alliance.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 939, 0, 1851107, 'Stonetalon Mountains', 'Travel to Stardust Spire', 'The Horde has been relentless in their conquest of Ashenvale.\n\nNow is the time for a decisive counterattack against their hold on Stonetalon Mountains.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 940, 0, 1851087, 'Southern Barrens', 'Aid Northwatch Hold', 'The Alliance has encountered heavy Horde resistance in the Southern Barrens.\n\nWe must hold against the Horde if we have any hope of pushing them out of Kalimdor and keeping our supply routes secure.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 948, 0, 1851111, 'Un\'Goro Crater', 'Assist the Expeditions', 'Un\'Goro Crater is a lush tropical environment that has many unique beasts and crystals all throughout its landscape.\n\nThe Marshal Expeditions is looking for help to study the land and gain a better understanding of the crater.', '', 32535);
INSERT INTO `playerchoice_response` (`ChoiceId`, `ResponseId`, `Index`, `ChoiceArtFileId`, `Header`, `Answer`, `Description`, `Confirmation`, `VerifiedBuild`) VALUES (352, 946, 0, 1851101, 'Felwood', 'Help Cleanse Felwood', 'The Burning Legion\'s corruption still taints Felwood, and its effects can be seen everywhere.\n\nStop the demon infestation and aid the Emerald Circle in cleansing the forest.', '', 32535);


DELETE FROM `playerchoice_response_reward` WHERE `ChoiceId`=352;
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 1014, 0, 0, 0, 0, 0, 0, 0, 0, 176352, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 937, 0, 0, 0, 0, 0, 0, 0, 0, 258548, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 953, 0, 0, 0, 0, 0, 0, 0, 0, 258550, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 954, 0, 0, 0, 0, 0, 0, 0, 0, 258552, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 938, 0, 0, 0, 0, 0, 0, 0, 0, 258553, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 956, 0, 0, 0, 0, 0, 0, 0, 0, 258554, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 939, 0, 0, 0, 0, 0, 0, 0, 0, 258555, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 957, 0, 0, 0, 0, 0, 0, 0, 0, 258556, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 940, 0, 0, 0, 0, 0, 0, 0, 0, 258557, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 941, 0, 0, 0, 0, 0, 0, 0, 0, 258558, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 943, 0, 0, 0, 0, 0, 0, 0, 0, 258560, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 958, 0, 0, 0, 0, 0, 0, 0, 0, 258567, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 960, 0, 0, 0, 0, 0, 0, 0, 0, 258569, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 961, 0, 0, 0, 0, 0, 0, 0, 0, 258570, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 962, 0, 0, 0, 0, 0, 0, 0, 0, 258571, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 963, 0, 0, 0, 0, 0, 0, 0, 0, 258572, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 964, 0, 0, 0, 0, 0, 0, 0, 0, 258573, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 965, 0, 0, 0, 0, 0, 0, 0, 0, 258574, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 966, 0, 0, 0, 0, 0, 0, 0, 0, 258575, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 967, 0, 0, 0, 0, 0, 0, 0, 0, 258576, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 969, 0, 0, 0, 0, 0, 0, 0, 0, 258578, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 970, 0, 0, 0, 0, 0, 0, 0, 0, 258579, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 976, 0, 0, 0, 0, 0, 0, 0, 0, 258585, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 977, 0, 0, 0, 0, 0, 0, 0, 0, 258586, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 989, 0, 0, 0, 0, 0, 0, 0, 0, 258598, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 972, 0, 0, 0, 0, 0, 0, 0, 0, 258608, 0);
INSERT INTO `playerchoice_response_reward` (`ChoiceId`, `ResponseId`, `TitleId`, `PackageId`, `SkillLineId`, `SkillPointCount`, `ArenaPointCount`, `HonorPointCount`, `Money`, `Xp`, `SpellId`, `VerifiedBuild`) VALUES (352, 1429, 0, 0, 0, 0, 0, 0, 0, 0, 281351, 0);
